# dbt/dbt_project.yml

name: 'elt_dataflow_n8n'
version: '1.0'
config-version: 2

profile: 'elt_dataflow_n8n'  # 🔥 Corrigido aqui!

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  sales_project:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
